sudo: false
language: node_js
node_js:
  - '10'
addons:
  ssh_known_hosts: 106.13.98.159
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_00a29d1b8a89_key -iv $encrypted_00a29d1b8a89_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa
  - ssh-add ./deploy_rsa
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
